spring:
  datasource:
    url: jdbc:h2:file:./connections
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true

  liquibase:
    change-log: classpath:liquibase/changelog.yaml
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
        web-admin-password: sa

logging:
  level:
    org:
      hibernate:
        type: INFO
    cz:
      jcode:
        dbviewer:
          aspect: DEBUG

cz:
  jcode:
    dbviewer:
      server:
        encryption-key: someKey76575467780-&*(%
        encryption-hex-salt-16-bytes: abcd1234abcd1234
        controller-logging-aspect:
          enabled: true

server:
  error:
    include-message: never
    include-stacktrace: never
